sudo: required
dist: trusty

language: go

matrix:
  include:
    - go: 1.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev qemu libvirt-bin -qq
  - cd `mktemp -d`
  - mkdir -p ${GOPATH}/src/github.com/hyperhq
  - wget https://git.fedorahosted.org/cgit/lvm2.git/snapshot/lvm2-2_02_131.tar.xz
  - tar xf lvm2-2_02_131.tar.xz
  - cd lvm2-2_02_131
  - ./configure && make device-mapper && sudo make install

# override the default `install`, otherwise default `install` will export ${TRAVIS_BUILD_DIR}/Godeps/_workspace as GOPATH
# see https://docs.travis-ci.com/user/languages/go#Dependency-Management

install:
  - cd ${TRAVIS_BUILD_DIR}
  - hack/install-grpc.sh
  - hack/verify-gofmt.sh
  - hack/verify-generated-proto.sh
  - ./autogen.sh && ./configure && make

script:
  - cd ${TRAVIS_BUILD_DIR} && hack/test-cmd.sh
